In [5]:
import numpy as np
import pandas as pd
import string

In [28]:
lines = open("testput.txt").read().splitlines()
lines

['abc', '', 'a', 'b', 'c', '', 'ab', 'ac', '', 'a', 'a', 'a', 'a', '', 'b']

In [29]:
def FillDataFrame(dataFrame, dictionary):
    return dataFrame.append(dictionary, ignore_index=True)

In [30]:
columns = list(string.ascii_lowercase)
print(columns)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [51]:
customDeclarationData = pd.DataFrame(columns=columns)

## Read from file and fill a row of data frame for each passport
dictionary = {}

with open("input.txt") as openFileObject:
    for line in openFileObject:
        if(line == '\n'):
            customDeclarationData = FillDataFrame(customDeclarationData, dictionary)
            dictionary.clear()
            continue
        
        for character in line.rstrip():
            dictionary[character] = True
    customDeclarationData = FillDataFrame(customDeclarationData, dictionary)
    dictionary.clear()

customDeclarationData = customDeclarationData.fillna(False)
customDeclarationData

,a,b,c,d,e,f,g,h,i,j,...,q,r,s,t,u,v,w,x,y,z
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,True,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,True,True,False,True,True,True,True,True,True,False,...,True,True,True,False,True,True,True,False,True,True
3,True,True,True,False,True,True,True,True,True,False,...,True,True,False,True,False,True,True,False,False,True
4,True,True,True,False,True,True,True,True,True,False,...,True,False,False,True,False,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,True,True,True,False,True,True,True,True,True,True,...,False,True,False,True,True,True,True,True,False,True
454,True,True,True,False,True,False,True,True,False,True,...,True,True,False,False,True,True,True,False,False,True
455,True,True,False,True,True,True,True,True,True,True,...,True,False,True,False,True,True,True,True,False,True
456,True,True,True,True,False,True,True,True,False,True,...,False,False,True,True,True,False,True,False,True,False
457,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,False,True,True

In [52]:
customDeclarationData.values.sum()

6416

In [78]:
def ReviseDictionaryEveryone(dictionary, numberOfPeople):
    for key in dictionary:
        if int(np.floor(dictionary[key] / numberOfPeople)):
            dictionary[key] = True
        else:
            dictionary[key] = False
    
    return dictionary

In [81]:
customDeclarationData_Everyone = pd.DataFrame(columns=columns)

## Read from file and fill a row of data frame for each passport
dictionary_Everyone = {}
numberOfPeople = 0

with open("input.txt") as openFileObject:
    for line in openFileObject:
        if(line == '\n'):
            dictionary_Everyone = ReviseDictionaryEveryone(dictionary_Everyone,numberOfPeople)
            customDeclarationData_Everyone = FillDataFrame(customDeclarationData_Everyone, dictionary_Everyone)
            dictionary_Everyone.clear()
            numberOfPeople = 0
            continue
        
        for character in line.rstrip():
            if character in dictionary_Everyone:
                dictionary_Everyone[character] += 1
            else:
                dictionary_Everyone[character] = 1
    
        numberOfPeople += 1
    dictionary_Everyone = ReviseDictionaryEveryone(dictionary_Everyone,numberOfPeople)
    customDeclarationData_Everyone = FillDataFrame(customDeclarationData_Everyone, dictionary_Everyone)
    dictionary_Everyone.clear()
    numberOfPeople = 0

customDeclarationData_Everyone = customDeclarationData_Everyone.fillna(False)
customDeclarationData_Everyone

,a,b,c,d,e,f,g,h,i,j,...,q,r,s,t,u,v,w,x,y,z
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,True,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,True,True,False,False,False,False,False,False,False,False
4,True,True,True,False,True,True,True,True,True,False,...,True,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,True,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,True,False,False,True
454,True,False,True,False,False,False,True,False,False,False,...,True,True,False,False,False,False,False,False,False,True
455,True,True,False,True,True,False,False,True,True,False,...,True,False,True,False,True,False,True,True,False,True
456,True,True,True,True,False,False,True,True,False,True,...,False,False,True,True,False,False,True,False,True,False
457,False,False,True,False,False,False,True,False,False,False,...,False,True,True,False,True,False,True,False,False,False

In [82]:
customDeclarationData_Everyone.values.sum()

3050